name: Deploy
on: [push]
jobs:
  deploy:
    name: "Deploy to netlify"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update -y && sudo apt-get install -y asciidoctor
      - run: sudo apt-get install -y linkchecker
      - run: make all
      - run: make main.html && linkchecker --check-extern ./main.html
      - uses: netlify/actions/cli@master
        with:
          args: deploy --prod --dir=./dist/
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

