name: menu
on: [push]
jobs:
  dire_bonjour:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@main
    - run: asciidoctor ./main.adoc
    - name: Publish
    - uses: netlify/actions/cli@main
      with:
        args: deploy --dir=site --functions = functions
      env:
        NETLIFY_SITE_ID: ${{secrets.NETLIFY_SITE_ID}}
        NETLIFY_AUTH_TOKEN: ${{secrets.NETLIFY_AUTH_TOKEN}}

    
