on: push
name: Publish on Netlify
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - run:  sudo apt-get install asciidoctor
    - run: asciidoctor ./main.adoc
    
    - uses: netlify/actions/cli@master
    - run: export NETLIFY_AUTH_TOKEN=yu055_xUsP19oiGPACHhdqBvwGb4grtH3UYshk5o5Rg
    - run: export NETLIFY_SITE_ID=744de9cb-de9b-4ba2-9123-7c0eb5487ed5
    - run: netlify deploy --prod --dir=../main.html
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

