on: push
name: Publish on Netlify
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - run:  sudo apt-get install asciidoctor
    - run: asciidoctor ./main.adoc
    - name: Publish
      uses: netlify/actions/cli@master
      with:
        args: deploy --dir=site --functions=functions
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

